### ISSUE TITLE
Calculate Net APY

### ISSUE THREAD

**Issue by edgarpavlovsky** [mrgnlabs/mrgn-ts#149]
Calculate the net APY users are getting on mrgnlend, netting their deposits and borrows

**Comment by andresmechali** [comment]
I'd like to work on this one

**Comment by jdubpark** [comment]
I see `apy: number` available in `AccountSummary` interface, calculated using [computeNetApy](https://github.com/mrgnlabs/mrgn-ts/blob/main/packages/marginfi-client-v2/src/account.ts#L721-L745).

Why not just add this snippet in [AccountSummary.tsx](https://github.com/jdubpark/mrgn-ts/blob/issue/frontend-net-apy/apps/marginfi-v2-ui/src/components/AccountSummary/AccountSummary.tsx#L48-L55)
```typescript
<AccountMetric
    label={"Net APY"}
    value={wallet.connected ? usdFormatter.format(accountSummary.apy) : "-"}
/>
```

**Comment by 50shadesofgwei** [comment]
heyo
are u still looking for someone to build this? I see that on the frontend it still says coming soon
