### ISSUE TITLE
[marginfi v2 ui] BUG: Inconsistent Withdrawal Behavior and Blocked Borrowing

### ISSUE THREAD

**Issue by k0beLeenders** [mrgnlabs/mrgn-ts#155]
**_Description:_**
On the lending tab of the UI, an issue arises when a user supplies a specific amount and then proceeds to the borrow tab to withdraw the same amount using the "max" button. The current implementation retrieves the value of "maxWithdraw" from the "activeBankInfo" object to determine the withdrawal amount. However, this value does not accurately align with the amount the user has supplied, resulting in an inconvenient situation.

The problem occurs when the withdrawal amount calculated from "maxWithdraw" is smaller than the total amount the user has supplied. As a consequence, a small residual amount remains in the lending pool, preventing the user from withdrawing the remaining balance and causing an obstruction in borrowing any further.

**_Expected Behavior:_**
The withdrawal functionality should accurately reflect the amount supplied by the user. When the "max" button is used on the borrow tab, it should consider the exact amount the user has lent, allowing for a complete withdrawal and enabling further borrowing if desired.

**_Steps to Reproduce:_**
- Navigate to the lending tab.
- Supply a specific amount, for example, 1 usdc.
- Go to the borrow tab.
- Click the "max" button to withdraw the maximum amount.
- Observe the withdrawal behavior and the remaining balance.

<img width="574" alt="marginfi_snippet" src="https://github.com/mrgnlabs/mrgn-ts/assets/32452483/f7101714-4ddf-4c0c-8ebb-0fd9c34a7589">

**Comment by losman0s** [comment]
This was since fixed over a few commits that:
- started accounting for the free collateral of the user in the calc
- introduced some volatility margin in the case where the withdrawable amount is capped by the free collateral (and not the position size)
- fixed a state discrepancy introducing an incorrect detection of which value was capping the withdrawable amount (free collat v position size)
