### ISSUE TITLE
Social Login

### ISSUE THREAD

**Issue by chambaz** [mrgnlabs/mrgn-ts#302]
- [x] web3 auth signin (email / twitter / google / apple)
- [x] social pfp if available
- [x] in-app wallet view (balance, tokens, links)
- [x] export private key
- [x] hotkeys conflicting with email input field
- [ ] moonpay onramp integration
- [ ] issue when user cancels signup, unable to continue with any provider
- [ ] state updates/refresh when funds transferred

**Comment by 0xmustapha** [comment]
state updates/refresh
