### ISSUE TITLE
[Bug] Maintain Backpack wallet connection on page refresh or revisit

### ISSUE THREAD

**Issue by jdubpark** [mrgnlabs/mrgn-ts#473]
Currently, refreshing or revisiting the Marginfi website disconnects the Backpack wallet. I've tested with the Phantom wallet and this behavior doesn't happen, ie. Phantom wallet remains connected through refreshes and revisits. It gets annoying to connect whenever visiting the Marginfi website.

"Sign in with Backpack" resets on refreshes or revisits.
<img width="1426" alt="Screenshot 2024-01-02 at 11 53 03 PM" src="https://github.com/mrgnlabs/mrgn-ts/assets/21009231/44da2e52-b56b-42c0-b733-5f17598a2c1d">

**Comment by ymittal** [comment]
I'm unable to reproduce this - are you still experiencing this?

**Comment by jdubpark** [comment]
The issue has been fixed, I believe. Works fine now.
