### ISSUE TITLE
[BUG] Website Loading Loop on Mobile Browsers

### ISSUE THREAD

**Issue by 0xemrekaya** [mrgnlabs/mrgn-ts#555]
When accessing the website from a computer, there are no issues; however, attempting to access it from a mobile device (using Safari, Chrome, or Phantom Wallet's built-in browser) results in an endless loading loop on the homepage, preventing the page from opening.

ScreenShot: 

1. ![IMG_1203](https://github.com/mrgnlabs/mrgn-ts/assets/72754835/a78f1f8c-a1fa-4995-9020-943a9135a8eb)

**Comment by edgarpavlovsky** [comment]
@chambaz @k0beLeenders

**Comment by 0xemrekaya** [comment]
> @chambaz @k0beLeenders 

Could you check this issue pls?
bcs i cant use marginfi website in my mobile phone, that's sucks.

**Comment by k0beLeenders** [comment]
@0xemrekaya is this resolved for you?
