### ISSUE TITLE
[marginfi v2 UI] fix accidental negative $0 account balance

### ISSUE THREAD

**Issue by edgarpavlovsky** [mrgnlabs/mrgn-ts#59]
A negative sign accidentally appears in the account balance:

![Screenshot 2023-02-19 at 8 50 26 PM](https://user-images.githubusercontent.com/12037214/219991148-686b35d7-8d07-4c79-abd4-4cf300190e43.png)

**Comment by rupalbohra** [comment]
Hey, I would like to try to solve this issue.

**Comment by edgarpavlovsky** [comment]
@rupalbohra all yours!
