### ISSUE TITLE
[marginfi v2 UI & marginfi landing page] Unify shared components into `mrgn-common`

### ISSUE THREAD

**Issue by edgarpavlovsky** [mrgnlabs/mrgn-ts#60]
The marginfi landing page is a stripped down fork of the marginfi v2 UI and reuses many components that can probably be consolidated into the `mrgn-common` library.

My hunch is that some components will be particularly useful to reuse across apps - like the `Navbar` component, e.g.:

* [marginfi-v2-ui implementation](https://github.com/mrgnlabs/mrgn-ts/tree/main/apps/marginfi-v2-ui/src/components/Navbar)
* [marginfi-landing-page implementation](https://github.com/mrgnlabs/mrgn-ts/tree/main/apps/marginfi-landing-page/src/components/Navbar)

It'd be helpful to start consolidating components to improve reusability

**Comment by dhruvsol** [comment]
Hey I can help with this @edgarpavlovsky
