### ISSUE TITLE
[marginfi v2 ui] `Repay` `max` button shows amount marginally too large

### ISSUE THREAD

**Issue by edgarpavlovsky** [mrgnlabs/mrgn-ts#68]
![Uploading Screenshot 2023-02-21 at 4.27.22 PM.png…]()

**Comment by losman0s** [comment]
Image does not display for me.
If it shows a specific account configuration I could try to replicate.

**Comment by losman0s** [comment]
Assuming this was fixed during the latest round of UI updates. Re-open if new reports come in.
