### ISSUE TITLE
[marginfi v2 ui] Squads Fuze wallet integration

### ISSUE THREAD

**Issue by jkbpvsc** [mrgnlabs/mrgn-ts#70]
From squads chat: 

![telegram-cloud-photo-size-4-6028327522011300558-y](https://user-images.githubusercontent.com/25896980/220472288-0fd35faa-3c2b-4d75-a4e6-5be60b04bdcb.jpg)

> Hey sirs, I've been testing Fuse with marginlend and ran into this bad boy.

https://user-images.githubusercontent.com/25896980/220472332-116580d5-a7ed-442d-b84c-ff3d9a1ce777.mp4

> Seems like your code checks for the wallet to not be a PDA which prevents multisig vaults from interacting with your app. Can someone take a look into it? We'd love for Fuse to work with marginlend from day one.

**Comment by losman0s** [comment]
This should have been resolved
