### ISSUE TITLE
[client] Load banks not defined in the config

### ISSUE THREAD

**Issue by jkbpvsc** [mrgnlabs/mrgn-ts#81]
Banks read by clients need to be defined in the config currently, this makes it incovenient to run liquidators safely, as they have to be updated with latest client versions.

Let liquidators still access new banks without having to update and restart them.

**Comment by losman0s** [comment]
As of recently there is no more static banks config in the SDK.
It was solely used to specify the token symbol for that bank, which is now done outside of the SDK, for instance in the dapp and liquidator by using an external cache.
As long as the consumer app does what is necessary to periodically fetch the latest banks, nothing in SDK hinders that process anymore.
